variables:
  BPBUILD_BUILDER_IMAGE: golang:1.23.4-alpine3.21
  BPBUILD_CERT_SECRET_NAME: banpu-co-th-tls
  BPBUILD_COMPONENT: api
  BPBUILD_INGRESS_PATH_PREFIX: starter-api/v2
  BPBUILD_INGRESS_TYPE: external
  BPBUILD_NAMESPACE: starter
  BPBUILD_RUNNER_IMAGE: alpine:3.15 # alpine:3.15
  BPBUILD_SERVICE: go-starter-api
  BPBUILD_DOCKER_FILE_NAME: go
  BPBUILD_REPOSITORY: go-starter-api
  BPBUILD_LIVENESS_PROBE_PATH: /health-check
include:
  - project: 'banpugroup/banpucom/build-pipeline/app-docker'
    ref: release/4.0.1
    file: 'pipeline.yml'
